### PR TITLE
Added compression (lossless) to images.

### PR DESCRIPTION
**Pull request by Mou-Ikkai**
Using Optipng and cwebp at max compression while being lossless, I reduced the filesize by a small amount!

### CODE REVIEW

**Review by AaronPinto — CHANGES_REQUESTED** [review]
Hey! Thanks for the PR. It appears the rewards.webp file was deleted/is missing.

**Comment by Mou-Ikkai** [comment]
> Hey! Thanks for the PR. It appears the rewards.webp file was deleted/is missing.

And this, kids, is why we don't trust github's own file upload button!

**Review by AaronPinto — APPROVED** [review]

**Comment by Mou-Ikkai** [comment]
Hold on

**Comment by AaronPinto** [comment]
Yeah, I was gonna ask if you could rebase this onto the latest changes

**Pull request closed without merging**
